### ISSUE TITLE
Not compatible with ARM64 (iOS, M1) chips 

### ISSUE THREAD

**Issue by awcchungster** [storj/uplink-c#7] opened 2021-11-15 22:19 UTC
Hi everyone,

I've been testing the iOS bindings and running into severe issues with the compilation and run step for this library. Has uplink-c bindings been tested with iOS or M1 devices? 

After my own testing, I believe it doesn't work. I've documented where I get stuck in [this ticket](https://github.com/storj-thirdparty/uplink-swift/issues/5). The bindings itself doesn't appear to be the problem, and it's related to the uplink-c compiler issues.

Has the Uplink-C library been tested with M1, or iOS devices? It is breaking when I run it.

**Comment by Erikvv** [comment] 2021-11-16 08:42
I have noticed you use GOOS=darwin. Why not GOOS=ios?

**Comment by Erikvv** [comment] 2021-11-16 09:57
Note to self: I am a confused w.r.t. to the CPU feature detection.

If I check this line: [/src/internal/cpu/cpu_arm64_other.go](https://github.com/golang/go/blob/6b3f4d388fe5602172f45361f438edf54699b953/src/internal/cpu/cpu_arm64_other.go) it seems a conditional include which I suspect should be true for iOS compilation.

However if I check this FreeBSD line: [/src/internal/cpu/cpu_arm64_freebsd.go](https://github.com/golang/go/blob/6b3f4d388fe5602172f45361f438edf54699b953/src/internal/cpu/cpu_arm64_freebsd.go#L5) this seems unconditional (only cpu architecture).

So how do I know that the FreeBSD code (which contains the illegal instruction) is not run for iOS?

**Comment by awcchungster** [comment] 2021-11-17 02:53
> I have noticed you use GOOS=darwin. Why not GOOS=ios? edit: Sorry I see in [golang/go#49553](https://github.com/golang/go/issues/49553) that you also tried GOOS=ios
> 
> You have done a good job diagnosing. The core of the issue seems that the register ID_AA64ISAR0_EL1 is read, but that this is not allowed in userspace, at least with this OS or CPU. This seems to be the offending line: https://github.com/golang/go/blob/6b3f4d388fe5602172f45361f438edf54699b953/src/internal/cpu/cpu_arm64.s#L10
> 
> We need to investigate why this is called in this case. I don't see an obvious control flow to the function. Then make a fix for it, through build instructions or possibly in the Go runtime.

In a version of Go (I believe due to M1), they moved from darwin to iOS. For good measure, I tested both. Please let me know how I can be helpful to resolve this. 

As a temporary workaround, I am using the AWSS3 Cocoapods SDK and using the Storj (minio) S3 gateway proxy.

**Comment by mniewrzal** [comment] 2021-11-30 12:50
@awcchungster 
We are working on this actively but we still need more time to prepare a solution.

**Comment by TopperDEL** [comment] 2021-11-30 12:56
Not sure if it is related - but might [this one](https://go-review.googlesource.com/c/go/+/360895/) cause your issue?

**Comment by Erikvv** [comment] 2021-12-09 13:14
> Not sure if it is related - but might this one cause your issue?

I don't think so.

There seems to be no issue on Mac OS on M1, gonna test iPhone soon.

**Comment by awcchungster** [comment] 2021-12-15 01:34
Hey @mniewrzal, any updates on the iOS solution? In addition the Swift access, could you also wrap this in react native? My and most apps I've seen are actually wrapped in react native to streamline development.

**Comment by mniewrzal** [comment] 2021-12-15 08:26
Hi @awcchungster 
We are still working on this. We have delay because we were waiting for the testing device.

**Comment by Erikvv** [comment] 2021-12-23 22:48
I was able to reproduce the issue wrt ID_AA64ISAR0_EL1, and I'm looking for a workaround.

It's possible to wrap for react-native, but it seems not directly, only through Swift or Objective-C (https://reactnative.dev/docs/native-modules-ios).

**Comment by awcchungster** [comment] 2021-12-24 02:32
Glad you found the same issue. 

On React Native, the Facebook team is going through a rewrite of the module. It's worth reviewing that to see if it impacts the longevity of the port. Otherwise, a connect to Swift makes sense as a starting point.

I still recommend React native as the end goal. Given the state of the ecosystem and from what I can see from tutorials/examples, devs are likely using higher level abstractions to launch apps quickly.

**Comment by awcchungster** [comment] 2021-12-24 02:33
Happy holidays and thank you so much!

**Comment by Erikvv** [comment] 2022-01-25 12:50
Uplink-c v1.2.2 did not work on iOS+Go 1.17 because golang.org/x/sys/cpu didn't, and because this package is mismatched with the Go runtime there is no possible combination of flags to make it compile with like it did with older go versions.

So the solution is simply to update uplink-c.

Closing this issue, but I'm making it a task to write missing documention for uplink-swift.

**Closed by Erikvv** 2022-01-25 12:50 UTC
